dataset:
  origin_adj_data_path: '../data/adjacency_matrix_grid.csv'
  io_adj_data_path: '../data/io_matrix_grid.npy'
  feature_matrix_data_path: '../data/feature_matrix_grid.npy'
  input_seq: 12
  output_seq: 1
  batch_size: 8
  device: cuda:0
  basic_interval: 5                    # minutes
  io_matrix_interval: 3                # hours
  split_rate: [7, 2, 1]

# Adam, AdamW, RMSprop
optimize:
  learning_rate: 0.001
  weight_decay: 0.0001
  name: Adam

trainer:
  K: 3
  epoch: 300
  theta: 0.5
  block_nums: 3
  drop_rate: 0.00
  adj_hidden_dim: 16
  kernel_size: [1, 3]
  in_channel_list: [2, 16, 8]
  out_channel_list: [16, 8, 2]
  in_tcn_dim_list: [2, 16, 8]
  out_tcn_dim_list: [2, 16, 8]
  model_path: '../saved_models'
  results_path: '../results'
